# Generated by Django 3.1.13 on 2021-10-01 00:59

import django.core.serializers.json
from django.db import migrations, models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0013_default_fallback_value_computedfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aquarium",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("length", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("volume", models.IntegerField(editable=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Aquarium Model",
                "verbose_name_plural": "Aquariums",
                "ordering": ["name"],
            },
        ),
    ]
